#!/bin/bash

########################################################################
# Copyright (C) 2013 - 2018 : Kathrin Hanauer                          #
#                                                                      #
# This file is part of Algora.                                         #
#                                                                      #
# Algora is free software: you can redistribute it and/or modify       #
# it under the terms of the GNU General Public License as published by #
# the Free Software Foundation, either version 3 of the License, or    #
# (at your option) any later version.                                  #
#                                                                      #
# Algora is distributed in the hope that it will be useful,            #
# but WITHOUT ANY WARRANTY; without even the implied warranty of       #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        #
# GNU General Public License for more details.                         #
#                                                                      #
# You should have received a copy of the GNU General Public License    #
# along with Algora.  If not, see <http://www.gnu.org/licenses/>.      #
#                                                                      #
# Contact information:                                                 #
#   http://algora.xaikal.org                                           #
########################################################################

if [ $# -lt 1 ]
then
	echo "Usage: $0 <PATH_TO_HEADER_FILE>"
	exit 1
fi

VERSION_HEADER=$1
[ -f "${VERSION_HEADER}" ] || eval 'echo "Version header file ${VERSION_HEADER} not found." 1>&2; exit 1'

[ -z "${GIT_CMD}" ] && GIT_CMD=$(which git 2>/dev/null)
[ -n "${GIT_CMD}" ] || eval 'echo Binary "git" not found. Please specify its location explicitly via the GIT_CMD variable." 1>&2; exit 1'

GIT_REVISION=$(${GIT_CMD} log --pretty=format:'%H' -n 1)
GIT_DATE=$(${GIT_CMD} log --pretty=format:'%ai' -n 1)

echo "Git revision: ${GIT_REVISION}"
echo "Git date: ${GIT_DATE}"

if grep -q $GIT_REVISION $VERSION_HEADER && grep -q "$GIT_DATE" $VERSION_HEADER
then
	echo "Git revision unchanged. No update required."
	exit 0
fi

GIT_REVISION_IN_HEADER="  static constexpr char GIT_REVISION[] = \"${GIT_REVISION}\";"
GIT_DATE_IN_HEADER="  static constexpr char GIT_DATE[] = \"${GIT_DATE}\";"

sed -i -e "s/^.*GIT_REVISION.*$/${GIT_REVISION_IN_HEADER}/" -e "s/^.*GIT_DATE.*$/${GIT_DATE_IN_HEADER}/" $VERSION_HEADER

